Repository vuejs-translations/docs-zh-cn, pull requests merged in 2022-10, with the labels that each got.

#560 Update performance.md
  src/guide/best-practices/performance.md
Labels: 代码修改 (建议直接提到英文站，我们会定期从英文站同步改动)

#565 fix:update vue-tsc link
  src/guide/scaling-up/tooling.md
  src/guide/typescript/overview.md
Labels: 从英文版同步

#576 Sync #9d2aa267
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/jobsMdPlugin.ts
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/index.ts
  src/guide/essentials/event-handling.md
  src/partners/components/PartnerCard.vue
  src/partners/components/type.ts
  src/partners/components/utils.ts
  src/partners/dreamonkey.md
  src/partners/partners.json
  src/public/images/partners/dreamonkey-hero.png
  src/public/images/partners/dreamonkey.png
  src/public/images/vueschool/bg-desktop.svg
  src/public/images/vueschool/bg-mobile.png
  src/public/images/vueschool/bg-tablet.svg
  src/public/images/vueschool/close.svg
  src/public/images/vueschool/vs-iso.svg
  src/public/images/vueschool/vs-logo.svg
  src/translations/index.md
Labels: 从英文版同步, 请使用 merge commit 合并

#593 themes page translation
  src/ecosystem/themes/ThemeListItem.vue
  src/ecosystem/themes/ThemePage.vue
  src/ecosystem/themes/ThemeProduct.vue
  src/ecosystem/themes/themes.json
Labels: 翻译
