Repository vuejs-translations/docs-zh-cn, pull requests merged in 2022-05, with the labels that each got.

#278 docs(api): review src/api/application.md
  src/api/application.md
Labels: 校对

#298 docs(api): review composition-api-lifecycle.md
  src/api/composition-api-lifecycle.md
Labels: 校对

#300 docs(api): review src/api/composition-api-setup.md
  src/api/composition-api-setup.md
Labels: 校对

#303 docs(api): review src/api/composition-api-depenency-injection.md and index.md
  src/api/composition-api-dependency-injection.md
Labels: 校对

#311 docs(api): review src/api/options-composition.md
  src/api/options-composition.md
Labels: 校对

#279 docs(api): translation src/api/built-in-directives.md completed
  src/api/built-in-directives.md
Labels: 校对

#331 docs(api): review src/api/reactivity-advanced.md
  src/api/reactivity-advanced.md
Labels: 校对

#268 docs(api): translation src/api/options-state.md completed
  src/api/options-state.md
Labels: 翻译

#336 docs(api): review src/api/custom-renderer.md
  src/api/custom-renderer.md
Labels: 校对

#339 Sync
  .vitepress/config.ts
  .vitepress/theme/components/VueSchoolBanner.vue
  .vitepress/theme/components/VueSchoolLink.vue
  .vitepress/theme/index.ts
  package.json
  pnpm-lock.yaml
  src/about/community-guide.md
  src/api/application.md
  src/guide/best-practices/performance.md
  src/guide/components/images/named-slots.png
  src/guide/components/props.md
  src/guide/extras/render-function.md
  src/guide/quick-start.md
  src/guide/reusability/custom-directives.md
  src/guide/scaling-up/ssr.md
  src/guide/scaling-up/testing.md
  src/guide/typescript/overview.md
  src/partners/partners.json
  src/public/_redirects
  src/tutorial/tutorial.data.ts
Labels: 从英文版同步, 请使用 merge commit 合并

#371 Translate hello-world example
  src/examples/src/hello-world/App/composition.js
  src/examples/src/hello-world/description.txt
Labels: 翻译

#372 Translate handling-input example
  src/examples/src/handling-input/App/composition.js
  src/examples/src/handling-input/App/template.html
  src/examples/src/handling-input/description.txt
Labels: 翻译

#368 Sync
  src/api/ssr.md
  src/guide/components/props.md
  src/guide/scaling-up/ssr.md
  src/tutorial/src/step-2/description.md
Labels: 从英文版同步, 请使用 merge commit 合并

#391 Translated preference switch
  .vitepress/theme/components/PreferenceSwitch.vue
Labels: 网络环境和本地化
