Repository vuejs-translations/docs-zh-cn, pull requests merged in 2022-03, with the labels that each got.

#129 docs: review src/guide/components/events.md
  src/guide/components/events.md
Labels: 校对

#88 review src/guide/scaling-up/ssr.md
  src/guide/scaling-up/ssr.md
Labels: 校对

#140 sync upstream
  src/guide/essentials/reactivity-fundamentals.md
  src/guide/introduction.md
  src/guide/reusability/custom-directives.md
Labels: 从英文版同步

#135 review: src/guide/components/slots.md
  src/guide/components/slots.md
Labels: 校对

#106 docs: review class-and-style.md
  src/guide/essentials/class-and-style.md
Labels: 校对

#147 review: src/guide/essentials/template-refs.md
  src/guide/essentials/template-refs.md
Labels: 校对

#154 review: src/guide/extras/animation.md (#153)
  src/guide/extras/animation.md
  src/guide/extras/demos/AnimateWatcher.vue
Labels: 校对

#158 review: src/guide/essentials/forms.md
  src/guide/essentials/forms.md
Labels: 校对

#159 review src/guide/essentials/list.md
  src/guide/essentials/list.md
Labels: 校对

#160 review: src/guide/scaling-up/testing.md
  src/guide/scaling-up/testing.md
Labels: 校对

#201 fixed: guide/essentials/reactivity-fundamentals.md
  src/guide/essentials/reactivity-fundamentals.md
Labels: 校对

#192 review: src/guide/extras/ways-of-using-vue.md
  src/guide/extras/ways-of-using-vue.md
Labels: 校对

#157 Sync upstream
  .github/contributing/writing-guide.md
  src/api/built-in-special-elements.md
  src/api/reactivity-advanced.md
  src/api/sfc-spec.md
  src/guide/essentials/component-basics.md
  src/guide/essentials/event-handling.md
  src/guide/essentials/reactivity-fundamentals.md
  src/guide/extras/web-components.md
  src/guide/scaling-up/ssr.md
  src/sponsor/index.md
  src/tutorial/src/step-8/App/template.html
  src/tutorial/src/step-8/_hint/App/template.html
  src/tutorial/src/step-8/description.md
Labels: 从英文版同步, 请勿使用 squash 合并

#196 review: src/guide/essentials/reactivity-fundamentals.md and template-syntax.md
  .vitepress/theme/styles/badges.css
  src/guide/essentials/reactivity-fundamentals.md
  src/guide/essentials/template-syntax.md
Labels: 校对

#191 review: src/guide/essentials/conditional.md and src/guide/scaling-up/routing.md
  src/guide/essentials/conditional.md
  src/guide/scaling-up/routing.md
Labels: 校对

#189 fixed: slots.md
  src/guide/components/slots.md
Labels: 校对
