Repository vuejs-translations/docs-zh-cn, pull requests merged in 2022-06, with the labels that each got.

#428 Sync
  src/about/team/members-partner.json
  src/ecosystem/themes/themes.json
  src/examples/utils.ts
  src/guide/built-ins/teleport.md
  src/guide/essentials/component-basics.md
  src/guide/essentials/event-handling.md
  src/guide/essentials/list.md
  src/guide/extras/web-components.md
  src/guide/quick-start.md
  src/guide/scaling-up/tooling.md
  src/guide/typescript/options-api.md
  src/partners/partners.json
  src/partners/tighten.md
  src/public/images/partners/tighten-dark.svg
  src/public/images/partners/tighten-hero.jpg
  src/public/images/partners/tighten.svg
Labels: 从英文版同步, 请使用 merge commit 合并

#294 fix(api): display bug
  src/api/ApiIndex.vue
  src/api/api.data.ts
Labels: 网络环境和本地化

#443 Sync
  src/api/ApiIndex.vue
  src/api/api.data.ts
  src/api/general.md
  src/guide/components/events.md
  src/guide/essentials/component-basics.md
  src/guide/essentials/computed.md
  src/guide/scaling-up/sfc.md
  src/guide/scaling-up/testing.md
  src/guide/typescript/overview.md
  src/partners/components/PartnerCard.vue
  src/partners/components/PartnerPage.vue
  src/partners/components/utils.ts
  src/partners/partners.json
Labels: 从英文版同步, 请使用 merge commit 合并

#446 translate prop drilling
  src/guide/components/provide-inject.md
Labels: 翻译

#450 Sync #ba5f0fb
  package.json
  pnpm-lock.yaml
  src/guide/best-practices/accessibility.md
  src/guide/built-ins/transition-group.md
  src/guide/essentials/class-and-style.md
  src/guide/essentials/list.md
  src/guide/extras/reactivity-in-depth.md
  src/guide/typescript/overview.md
  src/tutorial/TutorialRepl.vue
Labels: 从英文版同步, 请使用 merge commit 合并
