Repository vuejs-translations/docs-zh-cn, pull requests merged in 2022-09, with the labels that each got.

#536 Sync #2019035
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/components/Home.vue
  .vitepress/theme/index.ts
  src/partners/components/PartnerList.vue
  src/public/images/vuejsde-conf/close.svg
  src/public/images/vuejsde-conf/vuejsdeconf_banner_large_general.png
  src/public/images/vuejsde-conf/vuejsdeconf_banner_medium_general.png
  src/public/images/vuejsde-conf/vuejsdeconf_banner_small_general.png
Labels: 从英文版同步, 请使用 merge commit 合并

#537 Sync commit b392b068fb893e3ac6079710fe34decbde7a3be3
  src/guide/extras/reactivity-transform.md
  src/guide/typescript/composition-api.md
Labels: 从英文版同步

#539 feat: sync commit 6400d164f4b02d52080707e32e9a4152c7960ba5
  src/guide/quick-start.md
Labels: 从英文版同步

#541 Sync #b2d3a52
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/components/Home.vue
  .vitepress/theme/index.ts
  src/guide/quick-start.md
  src/guide/typescript/composition-api.md
Labels: 从英文版同步, 请使用 merge commit 合并

#542 chore: script to generate sync pr content
  package.json
  pnpm-lock.yaml
  scripts/sync.js
Labels: 协作与流程

#550 Sync #480c95a8
  src/guide/components/slots.md
  src/tutorial/src/step-8/App/template.html
  src/tutorial/src/step-8/_hint/App/template.html
Labels: 从英文版同步, 请使用 merge commit 合并

#555 Sync #6d2dc93f
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/index.ts
  src/api/options-lifecycle.md
  src/public/images/vueschool/bg-desktop.svg
  src/public/images/vueschool/bg-mobile.png
  src/public/images/vueschool/bg-tablet.svg
  src/public/images/vueschool/close.svg
  src/public/images/vueschool/vs-fw-bg-small.svg
  src/public/images/vueschool/vs-fw-bg.svg
  src/public/images/vueschool/vs-iso.svg
  src/public/images/vueschool/vs-logo.svg
Labels: 从英文版同步, 请使用 merge commit 合并

#558 chore:update @vue/repl version
  package.json
  pnpm-lock.yaml
Labels: 从英文版同步
