Repository vuejs-translations/docs-zh-cn, pull requests merged in 2023-02, with the labels that each got.

#637 translate todo in built-in-special-elements.md
  src/api/built-in-special-elements.md
Labels: 翻译

#639 translate todo in watchers.md
  src/guide/essentials/watchers.md
Labels: 翻译

#640 translate todo in composition-api.md
  src/guide/typescript/composition-api.md
Labels: 翻译

#659 fix(sitemap): bug error
  .vitepress/theme/components/SiteMap.vue
Labels: 网络环境和本地化

#645 Sync #38b3baa9
  src/api/ssr.md
  src/guide/best-practices/accessibility.md
  src/guide/essentials/class-and-style.md
  src/guide/essentials/forms.md
  src/guide/introduction.md
  src/partners/partners.json
Labels: 从英文版同步, 请使用 merge commit 合并

#661 Sync #f4ff2047
  .vitepress/theme/components/SiteMap.vue
  src/about/team/Member.ts
  src/about/team/members-core.json
  src/guide/essentials/reactivity-fundamentals.md
  src/guide/extras/composition-api-faq.md
  src/guide/quick-start.md
  src/guide/scaling-up/tooling.md
  src/guide/typescript/options-api.md
  src/guide/typescript/overview.md
  src/partners/components/PartnerLanding.vue
  src/partners/components/PartnerList.vue
  src/partners/partners.json
  src/translations/index.md
Labels: 从英文版同步, 请使用 merge commit 合并
